### ISSUE TITLE
Containers stopped building

### ISSUE THREAD

**Issue by jokajak** [angelnu/containers#116]
Per https://github.com/onedr0p/containers/releases/tag/2024.4.0, there is no longer a onedr0p alpine image which breaks at least the cni-plugins container. I discovered that the 1.5.1 container image has bad cni-plugins that error with exec format issues.

In the process of copying your work to update to 1.6.1 I discovered the onedr0p issue and thought I'd pass it along.

Thanks for your contribution!

**Comment by angelnu** [comment]
Thanks - changed to default alpine and it is working again.
